---
title: "Arctic_Lake_Analysis"
author: "Simon Topp"
date: "11/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(mapview)
library(sf)
library(feather)
library(furrr)
library(trend)
library(tictoc)

knitr::opts_chunk$set(echo = TRUE)
```

## Including Plots
## Lets try this all again but with a sample grid

```{r}
#### Make the sample grid
library(rnaturalearth)
land <- ne_countries(scale = 'medium', returnclass = 'sf') %>%
  st_crop(.,xmin = -179.99, ymin = 50, xmax = 179.99, ymax = 84) %>%
  filter(name_long != 'Iceland', name_long != 'Greenland')

land <- land %>% st_cast('MULTIPOLYGON') %>% st_cast('POLYGON')

points <- tibble(long = c(-177, -116, 82), lat = c(67, 60,62)) %>%
  st_as_sf(coords = c('long','lat'), crs = 4326)

land <- st_union(land) %>% st_cast('POLYGON') %>% st_as_sf() %>%
  st_join(points, left = F)

#mapview(land)

pf <-  st_read('data/in/PermFrost/UiO_PEX_PERZONES_5.0_20181128_2000_2016_NH/UiO_PEX_PERZONES_5.0_20181128_2000_2016_NH.shp')

# pf <- st_crop(st_make_valid(pf) %>% st_transform(4326), 
#               xmin = -179.99, ymin = 50, xmax = 179.99, ymax = 84)

sample <- st_sample(pf, 10000, type = 'hexagonal')

check <- sample %>% st_transform(4326) %>% st_intersection(.,land) %>%
  st_transform(st_crs(pf)) %>%
  st_as_sf() %>%
  st_join(pf %>% select(pf = EXTENT))

check <- st_buffer(check, 10000, nQuadSegs = 2)

check <- check %>% mutate(SampID = row_number(),
                          pfCode = as.numeric(factor(pf))) 

mapview(check, zcol = 'pf')

st_write(check, 'data/out/grid_samp/ArcticGridSamp.shp')

mapview(check)
sum(st_area(check))

check <- st_read('data/out/grid_samp/ArcticGridSamp.shp')
mapview(check, zcol = 'pf')
```


```{r cars}
# Pickens dataset 'data/out/Lakes_UCLA_Pick50.csv'
# Peckel dataset 'data/out/Lakes_UCLA.csv')'
lakes <- read_csv('data/out/Lakes_UCLA_Pick50.csv') %>%  
  select(ID = label, pf = pf_first, sampID = first, year = year_first, 
         area = area_sum, tempS = temp_median, precipS = precip_median, lith = lith_first, hybasID = HybasID_first, .geo) %>%
  mutate(area = round(area/1e6,5),
         precipS = round(precipS,3),
         tempS = round(tempS,3),
         lith = as.integer(lith),
         year = as.integer(year),
         pf = factor(pf, levels = c(1:4), labels = c('Cont.', 'Discon.', 'Spora.', 'Isol')))

## Fix the geo columns
lakes <- lakes %>% 
  separate(.geo, into = c('text', 'coords'), sep = ':\\[') %>% 
  separate(coords, into = c('long', 'lat'), sep = ',') %>% 
  mutate(long = as.numeric(long), 
         lat = gsub(lat, pattern = '\\]}', replacement = ''), 
         lat = as.numeric(lat)) %>%
  select(-text)

write_feather(lakes, 'data/out/lakes_UCLA_munged.feather')
lakes <- read_feather("data/out/lakes_UCLA_munged.feather")
```

## UCLA Exploration
```{r}
lakes <- read_feather("data/out/lakes_UCLA_munged.feather")

## Create a lake characteristic variable to attach to lakes later on
lakeChar <- lakes %>%
  group_by(ID, pf, sampID, lith, hybasID) %>%
  summarise(area = mean(area, na.rm = T),
            long = mean(long),
            lat = mean(lat))

check <- lakeChar %>% group_by(ID) %>% summarise(count = n()) %>% filter(count > 1)
check2 <- lakeChar %>% filter(ID %in% check$ID)

## Basically we have 180 lakes where the Lith varies, makes sense since we did lithography at the lake level and pf at the sample area level. Not a big deal, maybe just remove them later.

check <- lakes %>% group_by(ID) %>%
  summarise(count = n()) %>%
  filter(count > 10)

lakeTrends <- lakes %>%
  filter(ID %in% check$ID) %>%
  select(ID, year, area, tempS, precipS) %>%
  pivot_longer(-c(ID,year)) %>%
  arrange(ID,year) %>%
  group_by(ID, name) %>%
  nest() %>%
  mutate(mk = purrr::map(data, ~trend::mk.test(.$value)),
         tau = purrr::map(mk, 'estimates'),
         tau = purrr::map_dbl(tau, 'tau'),
         p.value = map_dbl(mk, 'p.value')) %>%
  select(-data,-mk)

## Just take the first lith for the 180 wher we have duplicates (kinda arbitrary, maybe reconsider later)

lakeTrends <- lakeTrends %>% left_join(lakeChar %>% arrange(lith) %>% distinct())
lakeTrends <- lakeTrends %>% mutate(change = ifelse(tau > 0 & p.value < 0.01, 'Increasing',
                                                    ifelse(tau < 0 & p.value < 0.01, 'Decreasing', 'No Change')),
                                    change = ifelse(is.na(change), 'No Change', change))

write_feather(lakeTrends, 'data/out/UCLATrends_Area_Precip_Temp_Pickens.feather')
lakeTrends <- read_feather('data/out/UCLATrends_Area_Precip_Temp.feather')

SampSummaries <- lakeTrends %>% ungroup() %>%
  #filter(name == 'area') %>%
  group_by(sampID, name) %>%
  summarise(total = n(),
            increasing = sum(change == 'Increasing', na.rm = T),
            decreasing = sum(change == 'Decreasing', na.rm = T),
            p.increasing =round(increasing/total,2),
            p.decreasing =round(decreasing/total,2))


samps.sf <- st_read('data/out/grid_samp/ArcticGridSamp.shp') %>%
  select(sampID = SampID)

SampSummaries <- SampSummaries %>% right_join(samps.sf)

arctic <- st_as_sf(maps::map("world", plot = FALSE, fill = TRUE, ylim = c(60,90))) %>%
  st_transform(st_crs(samps.sf))

p1 <- ggplot(arctic) +
  geom_sf() +
  geom_sf(data = SampSummaries %>% st_as_sf(), aes(fill = total, color = total), size = .3) +
  scale_fill_viridis_c(trans = 'log10', na.value = 'transparent') +
  scale_color_viridis_c(trans = 'log10', na.value = 'transparent') +
  theme(legend.position = 'top')

p2 <- ggplot(arctic) +
  geom_sf() +
  geom_sf(data = SampSummaries %>% st_as_sf(), aes(fill = p.decreasing, color = p.decreasing), size = .3) +
  scale_fill_viridis_c(trans = 'log10', na.value = 'transparent') +
  scale_color_viridis_c(trans = 'log10', na.value = 'transparent') +
  theme(legend.position = 'top')

p3 <- ggplot(arctic) +
  geom_sf() +
  geom_sf(data = SampSummaries %>% st_as_sf(), aes(fill = p.increasing, color = p.increasing), size = .3) +
  scale_fill_viridis_c(trans = 'log10', na.value = 'transparent') +
  scale_color_viridis_c(trans = 'log10', na.value = 'transparent') +
  theme(legend.position = 'top')

gridExtra::grid.arrange(p1,p2,p3, nrow = 1)

ggplot

sampSummSF <- sampCharSF %>% 
  inner_join(lakeChar %>% ungroup() %>% distinct(sampID, .keep_all = T)) %>%
  left_join(SampSummaries %>% st_set_geometry(NULL) %>%
              filter(name == 'count') %>% ungroup() %>%
              select(sampID, countTrend = trends)) #%>% st_centroid()

sampSummSF <- sampSummSF %>% filter(total > 3) %>% 
  mutate(p.increasing = ifelse(p.increasing < .2, NA, p.increasing),
         p.decreasing = ifelse(p.decreasing < .2, NA, p.decreasing))


ggplot(arctic) +
  geom_sf() +
  geom_sf(data = sampSummSF, aes(fill = total, color = total), size = .3) +
  scale_fill_viridis_c(trans = 'log10') +
  scale_color_viridis_c(trans = 'log10') +
  theme(legend.position = 'top')

ggplot(arctic) +
  geom_sf() +
  geom_sf(data = sampSummSF, aes(fill = p.decreasing, color = p.decreasing), size = .3) +
  scale_fill_viridis_c(na.value = 'transparent') +
  scale_color_viridis_c(na.value = 'transparent') +
  theme(legend.position = 'top')





lakeTrends %>% filter(name == 'area') %>%
  ggplot(aes(x = pf, fill = change)) + geom_bar(position = 'dodge') + 
  scale_y_log10()

lithLabeler <- tibble(lith = c(1:16), lith_lab = c("unconsolidated sediment", "basic volcanic", "siliciclastic sedimentary", "basic plutonic", "mixed sedimentary", "carbonate sedimentary", "acid volcanic", "metamorphics", "acid plutonic", "intermediate volcanic", "water bodies", "pyroclastics", "intermediate plutonic", "evaporites", "no data", "ice and glaciers")) 

lakeTrends %>% filter(name == 'area') %>% 
  left_join(lithLabeler) %>%
  ggplot(aes(x = change, fill = change)) + geom_bar() + scale_y_log10() +
  facet_wrap(~factor(lith_lab), scales = 'free')


check <- lakeTrends %>% select(ID, pf, name, lith, mean_area = area, change) %>%
  pivot_wider(names_from = name, values_from = change)

table(check$area, check$tempS)

ggplot(check, aes(x = pf, fill = area)) + geom_bar(position = 'dodge') + 
  scale_y_log10() +
  facet_wrap(~tempS, scales = 'free')







SampSummaries %>%
  select(sampID, p.increasing, p.decreasing) %>%
  pivot_longer(-sampID) %>%
  ggplot(aes(x = name, y = value, fill = name)) + geom_boxplot() +
  theme(legend.position = 'none')

## look at sample site characteristics
## clean up the lithographies real quick
check <- lakeChar %>% ungroup() %>% distinct(sampID, .keep_all = T) %>%
  group_by(lith) %>% summarise(count = n()) %>% filter(count > 30)

ggplot(arctic) +
  geom_sf() +
  geom_sf(data = sampCharSF %>% filter(lith %in% check$lith) %>%
            left_join(lithLabeler), 
          aes(color = lith_lab, fill = lith_lab)) +
  scale_fill_viridis_d(option = 'plasma') +
  scale_color_viridis_d(option = 'plasma')

ggplot(arctic) +
  geom_sf() +
  geom_sf(data = sampCharSF, 
          aes(color = pf, fill = pf)) +
  scale_fill_viridis_d(option = 'plasma') +
  scale_color_viridis_d(option = 'plasma')

sampSummSF %>% st_set_geometry(NULL) %>%
  select(sampID, pf, p.increasing, p.decreasing) %>%
  pivot_longer(-c(sampID, pf)) %>%
  ggplot(aes(x = pf, y = value, color = name)) +
  geom_boxplot()

sampSummSF %>% st_set_geometry(NULL) %>% left_join(lithLabeler) %>%
  filter(lith %in% check$lith) %>%
  select(sampID, lith_lab, p.increasing, p.decreasing) %>%
  pivot_longer(-c(sampID, lith_lab)) %>%
  ggplot(aes(x = lith_lab, y = value, color = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust =1))

  
library(leafgl)
library(leaflet)

cols = colour_values_rgb(sampSummSF$p.increasing, include_alpha = FALSE) / 255
m1 <- leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPoints(data = sampSummSF %>% st_transform(4326), fillColor = cols, group = "pts") 

cols = colour_values_rgb(sampSummSF$p.decreasing, include_alpha = FALSE) / 255
m2 <- leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPoints(data = sampSummSF %>% st_transform(4326), fillColor = cols, group = "pts") 

#leaflet() %>% addProvqTiles() %>% addGlPoints(data = sampSummSF, group = 'pts')
#  mapview(sampSummSF, zcol = 'p.increasing')
#m2 <- mapview(sampSummSF, zcol = 'p.decreasing')
m3 <- mapview(sampCharSF, zcol = 'pf')
m4 <- mapview(sampCharSF, zcol = 'lith')

leafsync::sync(m1,m2,m3,m4)


## Look at the number of lakes in each sample site each year
lakeCounts <- lakes %>%
  select(ID, year, sampID, tempS, precipS) %>%
  group_by(sampID, year) %>%
  summarise(count = n(),
            precip = mean(precipS, na.rm = T),
            temp = mean(tempS, na.rm = T))

ggplot(lakeCounts, aes(x = factor(year), y = count)) + geom_boxplot() + scale_y_log10()
ggplot(lakeCounts, aes(x = factor(year), y = precip)) + geom_boxplot() + scale_y_log10()
ggplot(lakeCounts, aes(x = factor(year), y = temp)) + geom_boxplot() + scale_y_log10()

check <- lakeCounts %>%
  group_by(sampID) %>% summarise(count = n()) %>%
  filter(count > 3)

lakeCounts <- lakeCounts %>%
  filter(sampID %in% check$sampID) %>%
  pivot_longer(-c(sampID,year)) %>%
  arrange(sampID,year) %>%
  group_by(sampID, name) %>%
  nest() %>%
  mutate(mk = purrr::map(data, ~trend::mk.test(.$value)),
         tau = purrr::map(mk, 'estimates'),
         tau = purrr::map_dbl(tau, 'tau'),
         p.value = map_dbl(mk, 'p.value')) %>%
  select(-data,-mk)

lakeCounts <- lakeCounts %>%
  mutate(trends = ifelse(tau > 0 & p.value < 0.01, 'Increasing',
                             ifelse(tau < 0 & p.value < 0.01, 'Decreasing','No Change')),
         trends = ifelse(is.na(trends), 'No Change', trends)) %>%
  inner_join(samps.sf) %>% st_as_sf()

p2 <- ggplot(lakeCounts, aes(x = trends, fill = trends)) + geom_bar() +
  scale_fill_viridis_d() +
  facet_wrap(~name, scales = 'free') +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position = 'none')

p1 <- ggplot(arctic) +
  geom_sf() +
  geom_sf(data = lakeCounts, aes(fill = trends, color =trends), size = .3) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  facet_wrap(~name) +
  theme(legend.position = 'top')

gridExtra::grid.arrange(p1,p2, nrow = 2, heights = c(1,.7))


leafsync::sync(mapview(lakeCounts, zcol = 'lakeCounts'), m3,m4, leaflet() %>% addProviderTiles('Esri.WorldImagery'))  

```


```{r}
lakes.summ <- lakes %>% 
  group_by(sampID, year, pf) %>%
  summarise(area = sum(area),
         count = n(),
         area.avg = mean(area, na.rm = T))

check <- lakes.summ %>%
  group_by(sampID) %>%
  summarise(count = n()) %>%
  filter(count > 15)

sampTrends <- lakes.summ %>%
  filter(sampID %in% check$sampID) %>%
  pivot_longer(c('area', 'count')) %>%
  arrange(year) %>%
  group_by(sampID, name,pf) %>%
  nest(.) %>%
  mutate(sens.area = purrr::map(data, ~trend::sens.slope(.$value)),
         slope = map_dbl(sens.area, 'estimates'),
         p.value = map_dbl(sens.area, 'p.value')) %>%
  select(-data,-sens.area)

sampTrends <- lakes.summ %>%
  filter(sampID %in% check$sampID) %>%
  pivot_longer(c('area', 'count', 'area.avg')) %>%
  arrange(year) %>%
  group_by(sampID, name, pf) %>%
  nest(.) %>%
  mutate(sens.area = purrr::map(data, ~trend::mk.test(.$value)),
         slope = purrr::map(sens.area, 'estimates'),
         slope = purrr::map_dbl(slope, 'tau'),
         p.value = map_dbl(sens.area, 'p.value')) %>%
  select(-data,-sens.area)

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

modeLith <- lakes %>% group_by(sampID) %>%
  summarise(lith = getmode(lith))
lithLabeler <- tibble(lith = c(1:16), lith_lab = c("unconsolidated sediment", "basic volcanic rocks", "siliciclastic sedimentary rocks", "basic plutonic rocks", "mixed sedimentary rocks", "carbonate sedimentary rocks", "acid volcanic rocks", "metamorphics", "acid plutonic rocks", "intermediate volcanic rocks", "water bodies", "pyroclastics", "intermediate plutonic rocks", "evaporites", "no data", "ice and glaciers")) 

sampTrends <- sampTrends %>% left_join(modeLith)
  
sampTrends <- sampTrends %>% mutate(tDir = ifelse(slope > 0, 'increasing', ifelse(slope < 0, 'decreasing', ifelse(p.value > 0.05, 'NoChange', NA))))


sampTrends %>% na.omit() %>%
  ggplot(aes(x = name, fill = tDir)) + geom_bar(position = 'dodge') +
  facet_wrap(~pf, scales = 'free')


samps.sf <- st_read('data/out/grid_samp/ArcticGridSamp.shp') %>%
  select(SampID) %>%
  right_join(sampTrends, by = c('SampID' = 'sampID'))

ggplot() +
  basemap(limits = 60)

samps.sf %>%
  ggplot(aes(y = slope, x = pf)) +
  geom_violin(draw_quantiles = .5) +
  ylim(-.05,.05) +
  facet_wrap(~name)

mapview(samps.sf %>% filter(name == 'count', p.value < 0.05) %>% 
          mutate(slope.dir = ifelse(slope > 0, 'increasing', ifelse(slope < 0, 'decreasing', NA))) %>% st_centroid(), zcol = 'slope.dir')
```


## Lets look at HydroAtlas vars

```{r}
lakeTrends <- lakeTrends  %>% left_join(
    foreign::read.dbf('data/in/Shapes/BasinATLAS_v10_lev09.dbf') %>%
    rename(hybasID = HYBAS_ID) %>%
    filter(hybasID %in% lakeTrends$hybasID)
  )

areaTrends <- lakeTrends %>% filter(name == 'area')

attribute = 'area'
areaTrends %>% select_('ID', var = attribute, 'change') %>%
  mutate(deciles = cut_number(var ,10)) %>%
  ggplot(aes(x = deciles, fill = change)) + geom_bar(position = 'dodge') +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
  

haPlotter <- function(att){
 areaTrends %>% select_('ID', var = att, 'change') %>%
  filter(!is.na(var)) %>%
  mutate(deciles = cut_number(var ,10)) %>%
  ggplot(aes(x = deciles, fill = change)) + geom_bar(position = 'dodge') +
  scale_y_log10() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(title = att)
}

haPlotterFact <- function(att){
 areaTrends %>% select_('ID', var = att, 'change') %>%
  filter(!is.na(var)) %>%
  mutate(var = factor(var)) %>%
  ggplot(aes(x = change, fill = change)) + geom_bar(position = 'dodge') +
  scale_y_log10() +
  facet_wrap(~var) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) 
}

haPlotter("area" )
haPlotterFact("tbi_cl_smj")
grep('tbi', names(areaTrends), value = T)
##Good ones, gwt_cm_sav, area, "prm_pc_sse" isn't too bad (only 4 groups though), 'slt_pc_sav', 'snd_pc_sav', 


areaTrends %>% st_as_sf(coords = c('long', 'lat'),crs =4326) %>%
  mapview(zcol = 'change')
```

