---
title: "02_UCLA_LakeAnalysis"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
bibliography: references.bib
---

```{r setup, include=FALSE}
library(tidyverse)
library(mapview)
library(sf)
library(feather)
library(furrr)
library(trend)
library(tictoc)

knitr::opts_chunk$set(echo = TRUE)
```

## Look at sample site fractional changes in water area

```{r}
lakes <- read_csv('data/out/AW_GEE_Exports/UCLA_Pick20_3year.csv') %>%
  select(sampID = SampID, area = area_sum, count, year = year_first) %>% mutate(Threshold = 'Ephemeral') %>%
  bind_rows(read_csv('data/out/AW_GEE_Exports/UCLA_Pick50_3year.csv') %>%
  select(sampID = SampID, area = area_sum, count, year = year_first) %>% mutate(Threshold = 'Seasonal')) %>%
  bind_rows(read_csv('data/out/AW_GEE_Exports/UCLA_Pick70_3year.csv') %>%
  select(sampID = SampID, area = area_sum, count, year = year_first) %>% mutate(Threshold = 'Permanent')) %>%
  mutate(area = round(area/1e6,5),
         Threshold = factor(Threshold, levels = c('Ephemeral', 'Seasonal', 'Permanent')))
  

sampMeans <- lakes %>% group_by(sampID, Threshold) %>%
  summarise(Mean_area = mean(area)) %>%
  filter(Mean_area > 0) %>%
  mutate(filtID = paste0(Threshold,"_",sampID))

filt <- lakes %>% mutate(filtID = paste0(Threshold,'_',sampID)) %>%
  filter(filtID %in% sampMeans$filtID) %>%
  group_by(filtID) %>%
  summarise(count = n()) %>%
  filter(count > 10)

tp <- lakes %>% mutate(filtID = paste0(Threshold,'_',sampID)) %>%
  filter(filtID %in% filt$filtID) %>%
  left_join(sampMeans) %>%
  mutate(frac_area = area/Mean_area) %>%
  select(-c(filtID, Mean_area)) %>%
  pivot_longer(c(area, count, frac_area))


tp <- tp %>%
  arrange(sampID, year) %>%
  group_by(sampID, name,Threshold) %>%
  nest() %>%
  mutate(sens = purrr::map(data, ~trend::sens.slope(.$value)),
         slope = purrr::map_dbl(sens, 'estimates'),
         p.value = map_dbl(sens, 'p.value')) %>%
  select(-data,-sens)


################
## Check out some random individual timeseries
lakeSamp = unique(lakes$sampID) %>% sample(.,3)

lakes %>% filter(sampID %in% lakeSamp) %>%
  mutate(Threshold = factor(Threshold, levels = c('area20','area50','area70'), labels = c('Ephemeral', 'Seasonal','Permanent'))) %>% 
  ggplot(aes(x = year, y = area, color = Threshold)) + geom_line() +
  labs(title = 'Example time series for three random sample sites', x = 'Year', y = 'Area (sq km)') +
  theme_bw() +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  facet_wrap(~sampID, scales = 'free')
  

write_feather(tp, 'data/out/Trends_Pick_Full.feather')
```

# Look at the trends spatially.

```{r}
tp <- read_feather('data/out/Trends_Pick_Full.feather')

samps.sf <- st_read('data/out/grid_samp/ArcticGridSamp.shp') %>%
  select(sampID = SampID) %>%
  rbind(st_read('data/out/grid_samp/nonPFsamp.shp') %>%
  select(sampID = SampID))


arctic <- st_as_sf(maps::map("world", plot = FALSE, fill = TRUE, ylim = c(55,90))) %>%
  st_transform(st_crs(samps.sf))

plotter <- function(var, thresh){
  tp %>%
    filter(name == var) %>%
    mutate(slope = ifelse(slope > thresh, thresh, ifelse(slope < -1*thresh, -1*thresh, slope))) %>%
    left_join(samps.sf) %>%
    st_as_sf() %>%
    ggplot() +
      geom_sf(data = arctic) +
      geom_sf(aes(color = slope, fill = slope)) +
      labs(title = var) +
      facet_wrap(~Threshold, nrow = 1)
}

p1 <- plotter('count', .5) + 
  scale_color_gradient2(mid = 'grey80', 
                        breaks = c(-0.5, -0.25, 0, 0.25, 0.5), 
                        labels = c('<-0.5', -0.25, 0, 0.25, '>0.5')) +
      scale_fill_gradient2(mid = 'grey80', 
                           breaks = c(-0.5, -0.25, 0, 0.25, 0.5), 
                        labels = c('<-0.5', -0.25, 0, 0.25, '>0.5')) +
  labs(title = expression(Lake~Count~(n~yr^-1 )), 
       fill = 'Trend', color = 'Trend') +
  ggthemes::theme_map() +
  theme(legend.position = 'right')

#p1

#ggsave('figures/countTrends.png', width = 6, height = 2.5, units = 'in')

p2 <- plotter('area', .1) + 
  scale_color_gradient2(mid = 'grey80', 
                        breaks = c(-0.1,-0.05, 0, 0.05,0.1), 
                        labels = c('<-0.1', -0.05, 0, 0.05, '>0.1')) +
      scale_fill_gradient2(mid = 'grey80', 
                           breaks = c(-0.1,-0.05, 0, 0.05,0.1), 
                        labels = c('<-0.1', -0.05, 0, 0.05, '>0.1')) +
  labs(title = expression(Area~Change~(km^2~yr^-1 )), 
       fill = 'Trend', color = 'Trend') +
  ggthemes::theme_map() +
  theme(legend.position = 'right')

#p2
#ggsave('figures/areaTrends.png', width = 6, height = 2.5, units = 'in')

p3 <- plotter('frac_area',0.01) + 
  scale_color_gradient2(mid = 'grey80',  
                        breaks = c(-0.01,-0.005, 0, 0.005,0.01), 
                        labels = c('<-1%', "-0.5%", "0%", "0.5%", '>1%')) +
  scale_fill_gradient2(mid = 'grey80',
                       breaks = c(-0.01,-0.005, 0, 0.005,0.01), 
                       labels = c('<-1%', "-0.5%", "0%", "0.5%", '>1%')) +
  labs(title = expression(Fractional~Change~(percent~yr^-1 )),
       fill = 'Trend', color = 'Trend') +
  ggthemes::theme_map() +
  theme(legend.position = 'right')

#p3
#ggsave('figures/Frac_areaTrends.png', width = 6, height = 2.5, units = 'in')


g <- gridExtra::grid.arrange(p1,p2,p3, nrow =3)

ggsave('figures/Change9Panel_3Year.png', plot = g, width = 8, height = 6, units = 'in')
```

## tie the above to sample-characteristic in hydroAtlas

```{r}
sampChar <- read_csv('data/out/AW_GEE_Exports/SampleSiteCharacteristics_Medians.csv') %>%
  select(-BurnArea, -BurnYear) %>%
  rename(sampID = SampID) %>%
  left_join(read_csv('data/out/AW_GEE_Exports/SampleSiteCharacteristics_Means.csv') %>%
              select(BurnArea, BurnYear, sampID = SampID))
  

check <- tp %>% filter(name == 'frac_area', Threshold == 'area70') %>%
  left_join(sampChar) %>%
  left_join(samps.sf) %>% st_as_sf()

check %>% filter(PFProb == 0) %>%
  mutate(trend = ifelse(slope > 0 , 'Pos', 'Neg')) %>%
  st_centroid() 

ggplot(check, aes(x = PFProb, y = slope)) + geom_hex() + scale_fill_viridis_c(trans = 'log10')

ggplot(check %>% filter(PFProb == 0), aes(x = slope)) + geom_histogram()

give.n <- function(x){
  return(c(y = 0.01, label = length(x))) 
  # experiment with the multiplier to find the perfect position
}
tp <- tp %>% mutate(Threshold = factor(Threshold, 
                                       levels = c('area20','area50','area70','area90'),
                                       labels = c('Ephemeral (20%)', 'Highly Seasonal (50%)', 'Seasonal (70%)', 'Permanent (90%)' )))

plotter <- function(att, cuts, pfProbH = 1.1, pfProbL = 0){
 sampChar %>%
    right_join(tp %>% filter(name == 'frac_area')) %>% #, 
                             #Threshold != 'Highly Seasonal (50%)')) %>%
    filter(PFProb >= pfProbL, PFProb < pfProbH) %>%
    select(sampID, Threshold, slope, var = att) %>%
    #mutate(quintiles1 = cut_number(var, 5)) %>%
    #mutate(quintiles1 = cut_interval(var, 5)) %>%
    mutate(quintiles1 = cut(var, breaks = cuts, right = F, include.lowest = T)) %>%
    filter(!is.na(var)) %>%
    ggplot(aes(x = quintiles1, y = slope)) + 
    geom_violin() +
    geom_boxplot(width = .1) +
    geom_hline(yintercept =  0, color = 'red') +
    stat_summary(fun.data = give.n, geom = "text", fun = median, hjust = 1.1) +
    coord_cartesian(ylim = c(-0.01,0.01)) +
    labs(x = att, y = 'Slope (% Area/year)') +
    facet_wrap(~Threshold, nrow = 1)
}

plotter('PermP') + labs(title = 'Permeability', x = 'Permeability')
ggsave('figures/PermPDist.png',width = 8.5, height = 4, units = 'in')


plotter('Porosity',pfProbL = 0.90)


plotter('sand', pfProbL = 0.7) + labs(title = 'Sand Soil Content in Continous Permafrost', x = 'Sand (g/kg)')
ggsave('figures/SandPFDist.png',width = 8.5, height = 4, units = 'in')

plotter('sand', pfProbH = 0.7) + labs(title = 'Sand Soil Content in Discontinous Permafrost', x = 'Sand (g/kg)')
ggsave('figures/SandDPFDist.png',width = 8.5, height = 4, units = 'in')


plotter('PFProb', cuts = c(0,0.01,.20,.50,.99,1)) + labs(title = 'Permafrost Probability', x = 'Permafrost Probablility (%)')

ggsave('figures/PFProbDist.png',width = 8.5, height = 4, units = 'in')

plotter('BurnArea', cuts = c(0,0.1,0.2,0.5,0.75,1)) + labs(title = 'Percent Area Burned since 2000', x = 'Burn Area (%)')


plotter('soc')
##Good ones, gwt_cm_sav, area, "prm_pc_sse" isn't too bad (only 4 groups though), 'slt_pc_sav', 'snd_pc_sav', 'ari_ix_sav
```


## Alternative viz

```{r}

filt <- sampMeans %>% filter(Threshold == 'area70') %>%
  filter(Mean_Area > 3)


tp %>% filter(name == 'frac_area', 
              Threshold == 'Seasonal (70%)') %>%
  left_join(sampChar) %>%
  ungroup() %>%
  #mutate(PFProb = cut_interval(PFProb, 100, labels = F)) %>%
  mutate(PFProb = cut(PFProb, breaks = c(0,0.01,.20,.50,.99,1), labels = F)) %>%
  ggplot(aes(x = PFProb, y = slope)) +
  #geom_point(alpha = .0) +
  stat_summary(
    fun.min = function(z) { quantile(z,0.25) },
    fun.max = function(z) { quantile(z,0.75) },
    geom = 'ribbon', alpha = .1) +
   stat_summary(fun = median, geom = 'line') +
  coord_cartesian(ylim = c(-.02,.01))



tp %>% filter(name == 'frac_area', 
              Threshold == 'area70') %>%
  left_join(sampChar) %>%
  ungroup() %>%
  mutate(PFProb = cut_interval(PFProb, 50)) %>%
  #mutate(PFProb = cut(PFProb, breaks = c(0,0.01,.20,.50,.99,1), labels = F)) %>%
  ggplot(aes(x = PFProb, y = slope)) +
  #geom_point(alpha = .0) +
  stat_summary(
    fun = median,
    fun.min = function(z) { quantile(z,0.25) },
    fun.max = function(z) { quantile(z,0.75) },
    geom = 'crossbar', alpha = .1) +
   stat_summary(fun = mean, geom = 'line') +
  coord_cartesian(ylim = c(-.02,.01))



```


## Look at appearing and disapearing lakes

```{r}
lakeDis <- read_feather("data/out/lakes_UCLA_munged_Pickens70.feather") %>%
  mutate(period = ifelse(year < 2010, 'y00-09','y10-19')) %>%
  group_by(ID, lat,long,period) %>%
  summarise(count = n()) %>%
  pivot_wider(values_from = count, names_from = period) 

lakeDis[is.na(lakeDis)] = 0

lakeDis <- lakeDis %>%
  mutate(stats = ifelse(`y00-09` > 5 & `y10-19` < 5, 'Diss',
                        ifelse(`y00-09` < 5 & `y10-19` > 5, 'Emerged',
                               ifelse(`y00-09` < 5 & `y10-19` < 5,
                                      'Unstable',"Stable"))))

lakeDis <- lakeDis %>%
  inner_join(read_feather("data/out/lakes_UCLA_munged_Pickens70.feather") %>%
                       distinct(ID, sampID, hybasID)) %>%
  inner_join(foreign::read.dbf('data/in/Shapes/BasinATLAS_v10_lev09.dbf') %>%
               rename(hybasID = HYBAS_ID))

plotter <- function(att){
  lakeDis %>%
    ungroup() %>%
    select(ID, stats, var = att) %>%
    mutate(quintiles = cut_interval(var,5)) %>%
    ggplot(aes(x = quintiles)) + geom_bar(position = 'dodge') +
    facet_wrap(~stats, scales = 'free')
}

plotter('prm_pc_sse')

lakeDis %>% filter(stats %in% c('Diss','Emerged','Unstable')) %>%
  left_join(lakeChar) %>%
  st_as_sf(coords = c('long', 'lat'), crs = 4326) %>%
  mapview(zcol = 'stats')

sampDis <- lakeDis %>% filter(stats %in% c('Diss','Emerged','Unstable')) %>%
  left_join(read_feather("data/out/lakes_UCLA_munged_Pickens70.feather")) %>%
  group_by(sampID) %>%
  summarise(Diss = sum(stats == 'Diss'),
            Emerged = sum(stats == 'Emerged'),
            Unstable = sum(stats == 'Unstable'))

plotter <- function(i){
  sampDis %>%
    left_join(samps.sf) %>%
    st_as_sf() %>%
    ggplot() +
      geom_sf(data = arctic) +
      geom_sf(aes_string(color = i, fill = i)) +
  scale_fill_viridis_c(direction = -1, trans = 'log10', na.value = 'transparent') +
  scale_color_viridis_c(direction = -1, trans = 'log10', na.value = 'transparent')
  }
p1 <- plotter('Diss')
p2 <- plotter('Emerged')

gridExtra::grid.arrange(p1,p2, nrow = 1)
plotter('Unstable')

```


